[package]
name = "rust_trace"
version = "0.1.0"
authors = ["mlunnay"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
png = "0.15.0"
noise = "0.6.0"
rayon = "1.2.0"